"""add document provenance

Revision ID: 77de48cd5ef1
Revises: 91224c29b35f
Create Date: 2026-08-20 17:23:22.534959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77de48cd5ef1'
down_revision: Union[str, Sequence[str], None] = '91224c29b35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator_observations', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'indicator_observations', 'source_documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'source_documents', 'data_sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_documents', type_='foreignkey')
    op.drop_constraint(None, 'indicator_observations', type_='foreignkey')
    op.drop_column('indicator_observations', 'document_id')
    # ### end Alembic commands ###
