"""add observation uniqueness constraint

Revision ID: 9575663167bb
Revises: 4ab4bb0b5ab8
Create Date: 2026-08-20 13:57:42.557683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9575663167bb'
down_revision: Union[str, Sequence[str], None] = '4ab4bb0b5ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
